version: '3.8'
services:
  movies:
    image: devopsbysarvesh/amazonmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: devopsbysarvesh/amazontrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: devopsbysarvesh/amazondth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: devopsbysarvesh/amazonrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
