version: '3.8'
services:
  movies:
    image: devopsbysarvesh/paymovies:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: devopsbysarvesh/paytrain:v1
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: devopsbysarvesh/paydth:v1
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: devopsbysarvesh/payrecharge:v1
    ports:
      - "84:80"
    deploy:
      replicas: 3
